version: '3.8'
services:
  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: testdb
    # 【新增这一段】给 MySQL 瘦身，关闭性能看板，限制缓存池为 64M
    command:
      - --performance_schema=OFF
      - --innodb_buffer_pool_size=64M
    ports:
      - "3306:3306"

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: 123456
      DB_NAME: testdb
    depends_on:
      - db